name: Build and Release

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        arch: [amd64, arm64]

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.3'  # Specify the Go version

      - name: Create directories and build binaries
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: v1.0-${{ github.sha }}
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          for file in build/*; do
            echo "Uploading $file..."
            gh release upload ${{ steps.create_release.outputs.tag_name }} "$file" --clobber
          done

      - name: List all files in build directory
        run: ls build/