name: Build and Release

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        arch: [amd64, arm64]

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y)
            sudo mkdir -p -m 755 /etc/apt/keyrings
            wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null
            sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            sudo apt update
            sudo apt install gh -y
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew install gh
          fi

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.3'  # Specify the Go version

      - name: Create directories and build binaries
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: List all files in build directory
        run: ls build/

  create_release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: v1.0-${{ github.sha }}
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          for file in build/*; do
            echo "Uploading $file..."
            gh release upload ${{ steps.create_release.outputs.tag_name }} "$file" --clobber
          done